server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      webApi:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 15000
      idle-timeout: 300000
      max-lifetime: 1800000
      auto-commit: false
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.fetch_size: 150
      jakarta.persistence.query.timeout: 2500
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    table: migrations_history

cloud:
  storage:
    tasks-bucket-name: ${TASK_UPLOADS_LOCATION}
    presigned-url-expiration-minutes: 15
  messaging:
    enabled: true
    file-uploaded-queue-name: ${FILE_UPLOADED_QUEUE_NAME}
  aws:
    enabled: true
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    endpoint: http://${AWS_HOST}:${LOCALSTACK_PORT}
    s3:
        public-endpoint: http://${AWS_HOST}:${LOCALSTACK_PORT}
        path-style-access-enabled: true
    sqs:
        # default for all queues
        max-concurrent-messages: 3
        max-messages-per-poll: 2
        max-delay-between-polls: 1000ms

app:
  async:
    job-runner:
      restartDelayMs: 2500

modules:
  task:
    worker:
      num-workers: ${TASK_MODULE_NUM_WORKERS}
      loop-delay-range-ms-min: ${TASK_MODULE_WORKER_LOOP_DELAY_MIN}
      loop-delay-range-ms-max: ${TASK_MODULE_WORKER_LOOP_DELAY_MAX}