server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      webApi:
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
        dialect: org.hibernate.dialect.MySQLDialect

cloud:
  storage:
    tasks-bucket-name: text-processor-uploads
    presigned-url-expiration-minutes: 15
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    endpoint: http://${AWS_HOST}:${LOCALSTACK_PORT}
    s3:
        public-endpoint: http://${AWS_HOST}:${LOCALSTACK_PORT}
        path-style-access-enabled: true
    sqs:
        queue-name: text-processor-tasks